### PR TITLE
feat: submit idea completion screen

### PR DESCRIPTION
**Pull request by BenjaminYong**
## Purpose

A submit idea completion screen rather than an alert box.

## Changes

- Removed alert box on form submit.
- Routed form submission to a submit idea completion screen
- Reused some styling from action completion screen with the use of confetti.

### Screenshots

120456307_945936115896158_1699452110287664027_n

ezgif com-gif-maker (1)

## Checklist

- [x] Tested on Android
- [ ] Tested on iOS
- [x] Tested on Web

### CODE REVIEW

**Comment by jonowu** [comment]
Gonna wait until I merge in the typography before approving this one. We should probably avoid using the red from now on too

**Comment by BenjaminYong** [comment]
Hey @jonowu , now that typography has been merged, what needs to be done to complete this feature?

**Comment by jonowu** [comment]
> Hey @jonowu , now that typography has been merged, what needs to be done to complete this feature?

You should be able to delete the `ThankYouHeader` and `ThankYouDescription` now and use the typography components instead :)

**Comment by BenjaminYong** [comment]
> > Hey @jonowu , now that typography has been merged, what needs to be done to complete this feature?
> 
> You should be able to delete the `ThankYouHeader` and `ThankYouDescription` now and use the typography components instead :)

Sweet thanks mate, all done :)

**Review by jonowu — APPROVED** [review]
LGTM

**Pull request merged**
